[package]
name = "stream"
version = "0.1.0"
authors = ["Colton Donnelly <colton@donn.io>"]
edition = "2018"

[dependencies]
clap = { version = "2", features = [] }
either = "1"
handlebars = "3"
nom = "6.1"
once_cell = "1"
